### PR TITLE
remove duplicated code within the function

### PR DESCRIPTION
**Pull request by IvanWilli**
Hi Giorgio
I made some changes in vignette. Specifically, deleted some code duplicated inside the main function. Also fixed some grammatical issues.
Best

### CODE REVIEW

**Comment by spedygiorgio** [comment]
there were some git conflicts with master please have a look if it works now

**Comment by IvanWilli** [comment]
great. thanks

**Comment by spedygiorgio** [comment]
So, it works right...?

Il ven 15 mag 2020, 22:54 Iván Williams <notifications@github.com> ha
scritto:

> great. thanks
>
> El vie., 15 may. 2020 a las 17:17, Giorgio Alfredo Spedicato (<

**Comment by IvanWilli** [comment]
Yes, perfectly.
I dont´see the final vignette in the actualized cran repo (
https://cran.r-project.org/web/packages/lifecontingencies/vignettes/PensionPlanVal.html).
But I assume ithis s because you need to refresh it. It´s not urgent, so
maybe when you need it for other reasons.
best,
Iván

**Pull request merged**
